name: Build & Deploy
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
          name: build-files
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build project
        uses: actions/download-artifact@v4
        with:
          name: build-files
