name: Deployment React App
on:
  push:
    branches:
      - master
    # paths-ignore:
    #   - ".github/workflows/*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
      - name: Lint application
        run: npm run lint
      - name: Deploy application
        run: echo Deploying...
